version: "3.3"
services:
  influxdb:
    image: "influxdb:1.8"
    container_name: influxdb
    environment:
      TZ: ${TZ}
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin123
    restart: unless-stopped
    volumes:
      - ${PWD}/influxdb:/var/lib/influxdb
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 24
    ports:
      - 8086:8086
  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    user: "$PUID:$PGID"
    depends_on:
      - influxdb
    volumes:
      - ${PWD}/grafana:/var/lib/grafana
    ports:
      - 3000:3000
  rtl433:
    image: hertzg/rtl_433:latest
    depends_on:
      - influxdb
    devices:
      - '/dev/bus/usb'
    command:
      - '-Mtime:unix:usec:utc'
      - '-Mbits'
      - '-Mlevel'
      - '-Mprotocol'
      - '-Mstats:2:300'
      - '-Finflux://influxdb:8086/write?db=data&p=data&u=submit'
